import { FILE_KINDS } from '@chaff/common/enums/review.enums';
import type { FileKind } from '@chaff/common/enums/review.enums';

const GENERATED_PATHS = [
  /(^|\/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb?|npm-shrinkwrap\.json|composer\.lock|Gemfile\.lock|poetry\.lock|Pipfile\.lock|uv\.lock|Cargo\.lock|go\.sum|flake\.lock|mix\.lock|pubspec\.lock|Podfile\.lock|packages\.lock\.json)$/,
  /\.min\.(js|css)$/,
  /\.map$/,
  /(^|\/)(dist|build|out|vendor|node_modules|__generated__|generated)\//,
  /\.snap$/,
  /\.pb\.go$/,
  /_pb2\.py$/,
  /\.g\.dart$/,
  /\.generated\.\w+$/,
  /\.designer\.cs$/i,
  /(^|\/)migrations\/meta\/[^/]+\.json$/,
];
const TEST_PATHS = [
  /(^|\/)(__tests__|tests?|spec|specs|e2e)\//,
  /[._-](test|spec)\.\w+$/,
  /_test\.go$/,
  /(^|\/)test_[^/]+\.py$/,
  /Tests?\.(cs|java|kt)$/,
];
const DOCS_PATHS = [/\.(md|mdx|rst|txt|adoc)$/i, /(^|\/)docs?\//];
const CONFIG_PATHS = [
  /\.(json|jsonc|ya?ml|toml|ini|cfg|conf|env|properties|xml|lock|csproj|sln|gradle)$/i,
  /(^|\/)(Dockerfile|Makefile|\.gitlab-ci\.yml|\.gitignore|\.gitattributes|\.editorconfig|\.npmrc|\.nvmrc)$/,
  /(^|\/)\.github\//,
];
const GENERATED_MARKER = /@generated|DO NOT EDIT|auto-generated|autogenerated/i;
const MARKER_SEARCH_LENGTH = 600;

/** Classifies a changed file by its path; generated-file markers are checked separately once content is read. */
export function classifyPath(path: string, isBinary: boolean): FileKind {
  if (isBinary) return FILE_KINDS.BINARY;
  if (GENERATED_PATHS.some((pattern) => pattern.test(path))) return FILE_KINDS.GENERATED;
  if (TEST_PATHS.some((pattern) => pattern.test(path))) return FILE_KINDS.TEST;
  if (DOCS_PATHS.some((pattern) => pattern.test(path))) return FILE_KINDS.DOCS;
  if (CONFIG_PATHS.some((pattern) => pattern.test(path))) return FILE_KINDS.CONFIG;
  return FILE_KINDS.SOURCE;
}

/** True when the start of the file says it was generated by a tool. */
export function hasGeneratedMarker(content: string) {
  return GENERATED_MARKER.test(content.slice(0, MARKER_SEARCH_LENGTH));
}
