/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as StackRouteImport } from './routes/stack';
import { Route as FindingsRouteImport } from './routes/findings';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ReviewsSnapshotIdRouteImport } from './routes/reviews.$snapshotId';
import { Route as ReviewsSnapshotIdIndexRouteImport } from './routes/reviews.$snapshotId.index';
import { Route as ReviewsSnapshotIdDiffRouteImport } from './routes/reviews.$snapshotId.diff';

const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any);
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ReviewsSnapshotIdRoute = ReviewsSnapshotIdRouteImport.update({
  id: '/reviews/$snapshotId',
  path: '/reviews/$snapshotId',
  getParentRoute: () => rootRouteImport,
} as any);
const ReviewsSnapshotIdIndexRoute = ReviewsSnapshotIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewsSnapshotIdRoute,
} as any);
const ReviewsSnapshotIdDiffRoute = ReviewsSnapshotIdDiffRouteImport.update({
  id: '/diff',
  path: '/diff',
  getParentRoute: () => ReviewsSnapshotIdRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/findings': typeof FindingsRoute;
  '/stack': typeof StackRoute;
  '/reviews/$snapshotId': typeof ReviewsSnapshotIdRouteWithChildren;
  '/reviews/$snapshotId/diff': typeof ReviewsSnapshotIdDiffRoute;
  '/reviews/$snapshotId/': typeof ReviewsSnapshotIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/findings': typeof FindingsRoute;
  '/stack': typeof StackRoute;
  '/reviews/$snapshotId/diff': typeof ReviewsSnapshotIdDiffRoute;
  '/reviews/$snapshotId': typeof ReviewsSnapshotIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/findings': typeof FindingsRoute;
  '/stack': typeof StackRoute;
  '/reviews/$snapshotId': typeof ReviewsSnapshotIdRouteWithChildren;
  '/reviews/$snapshotId/diff': typeof ReviewsSnapshotIdDiffRoute;
  '/reviews/$snapshotId/': typeof ReviewsSnapshotIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/findings'
    | '/stack'
    | '/reviews/$snapshotId'
    | '/reviews/$snapshotId/diff'
    | '/reviews/$snapshotId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/findings'
    | '/stack'
    | '/reviews/$snapshotId/diff'
    | '/reviews/$snapshotId';
  id:
    | '__root__'
    | '/'
    | '/findings'
    | '/stack'
    | '/reviews/$snapshotId'
    | '/reviews/$snapshotId/diff'
    | '/reviews/$snapshotId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  FindingsRoute: typeof FindingsRoute;
  StackRoute: typeof StackRoute;
  ReviewsSnapshotIdRoute: typeof ReviewsSnapshotIdRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stack': {
      id: '/stack';
      path: '/stack';
      fullPath: '/stack';
      preLoaderRoute: typeof StackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/findings': {
      id: '/findings';
      path: '/findings';
      fullPath: '/findings';
      preLoaderRoute: typeof FindingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reviews/$snapshotId': {
      id: '/reviews/$snapshotId';
      path: '/reviews/$snapshotId';
      fullPath: '/reviews/$snapshotId';
      preLoaderRoute: typeof ReviewsSnapshotIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reviews/$snapshotId/': {
      id: '/reviews/$snapshotId/';
      path: '/';
      fullPath: '/reviews/$snapshotId/';
      preLoaderRoute: typeof ReviewsSnapshotIdIndexRouteImport;
      parentRoute: typeof ReviewsSnapshotIdRoute;
    };
    '/reviews/$snapshotId/diff': {
      id: '/reviews/$snapshotId/diff';
      path: '/diff';
      fullPath: '/reviews/$snapshotId/diff';
      preLoaderRoute: typeof ReviewsSnapshotIdDiffRouteImport;
      parentRoute: typeof ReviewsSnapshotIdRoute;
    };
  }
}

interface ReviewsSnapshotIdRouteChildren {
  ReviewsSnapshotIdDiffRoute: typeof ReviewsSnapshotIdDiffRoute;
  ReviewsSnapshotIdIndexRoute: typeof ReviewsSnapshotIdIndexRoute;
}

const ReviewsSnapshotIdRouteChildren: ReviewsSnapshotIdRouteChildren = {
  ReviewsSnapshotIdDiffRoute: ReviewsSnapshotIdDiffRoute,
  ReviewsSnapshotIdIndexRoute: ReviewsSnapshotIdIndexRoute,
};

const ReviewsSnapshotIdRouteWithChildren =
  ReviewsSnapshotIdRoute._addFileChildren(ReviewsSnapshotIdRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindingsRoute: FindingsRoute,
  StackRoute: StackRoute,
  ReviewsSnapshotIdRoute: ReviewsSnapshotIdRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
