import { Enumwaii } from '@chaff/enumwaii/enumwaii';
import type { InferEnumwaii } from '@chaff/enumwaii/enumwaii';

const errorCodesEnumwaii = new Enumwaii('ErrorCode', [
  'INTERNAL_SERVER_ERROR',
  'WORKSPACE_NOT_FOUND',
  'WORKSPACE_ALREADY_ADDED',
  'DIRECTORY_NOT_FOUND',
  'NOT_A_GIT_REPOSITORY',
  'GIT_UNAVAILABLE',
  'UNSUPPORTED_EXTERNAL_URL',
  'BRANCH_NOT_FOUND',
  'INVALID_PARENT_BRANCH',
  'NO_COMMON_ANCESTOR',
  'REVIEW_TARGET_NOT_FOUND',
  'SNAPSHOT_NOT_FOUND',
  'SNAPSHOT_FILE_NOT_FOUND',
  'UNIT_NOT_FOUND',
  'FINDING_NOT_FOUND',
  'INVALID_FINDING_ANCHOR',
  'INVALID_FINDING_STATUS',
  'DIGEST_NOT_FOUND',
  'DIGEST_ALREADY_RUNNING',
  'DIGEST_RUNNER_UNAVAILABLE',
  'PARENT_CYCLE',
  'BRANCH_NOT_CHECKED_OUT',
  'CONNECTION_NOT_FOUND',
  'CONNECTION_REJECTED',
  'CODE_HOST_UNREACHABLE',
  'CODE_HOST_ERROR',
  'REMOTE_PROJECT_NOT_FOUND',
  'CHANGE_REQUEST_NOT_FOUND',
  'CHANGE_REQUEST_ALREADY_LINKED',
  'SECRETS_UNAVAILABLE',
  'CODE_HOST_WRITE_REJECTED',
  'REVIEW_ALREADY_PENDING',
  'NOT_A_CHANGE_REQUEST',
  'NOTHING_TO_POST',
  'INVALID_AGENT_REPORT',
  'FIX_NOT_FOUND',
  'FIX_ALREADY_RUNNING',
  'FIX_STILL_RUNNING',
  'NOTHING_TO_FIX',
  'PREFERENCE_NOT_FOUND',
  'SHORTCUT_CONFLICT',
  'CHANGE_UNIT_NOT_FOUND',
]);

export const errorCodes = errorCodesEnumwaii.enum;
export type ErrorCodesType = InferEnumwaii<typeof errorCodesEnumwaii>;

export const errorMessages = errorCodesEnumwaii.derive({
  [errorCodes.INTERNAL_SERVER_ERROR]: 'An unexpected error occurred',
  [errorCodes.WORKSPACE_NOT_FOUND]: 'Repository not found',
  [errorCodes.WORKSPACE_ALREADY_ADDED]: 'This repository is already added',
  [errorCodes.DIRECTORY_NOT_FOUND]: 'Folder not found',
  [errorCodes.NOT_A_GIT_REPOSITORY]: 'This folder is not a git repository',
  [errorCodes.GIT_UNAVAILABLE]: 'git is not installed or not on PATH',
  [errorCodes.UNSUPPORTED_EXTERNAL_URL]: 'This link cannot be opened',
  [errorCodes.BRANCH_NOT_FOUND]: 'Branch not found in the repository',
  [errorCodes.INVALID_PARENT_BRANCH]: 'A branch cannot be reviewed against itself',
  [errorCodes.NO_COMMON_ANCESTOR]: 'The branch and its parent share no history',
  [errorCodes.REVIEW_TARGET_NOT_FOUND]: 'Review not found',
  [errorCodes.SNAPSHOT_NOT_FOUND]: 'Snapshot not found',
  [errorCodes.SNAPSHOT_FILE_NOT_FOUND]: 'File not found in this snapshot',
  [errorCodes.UNIT_NOT_FOUND]: 'Unit not found in this snapshot',
  [errorCodes.FINDING_NOT_FOUND]: 'Finding not found',
  [errorCodes.INVALID_FINDING_ANCHOR]: 'The lines to comment on are not part of this snapshot',
  [errorCodes.INVALID_FINDING_STATUS]: 'The finding cannot move to that status',
  [errorCodes.DIGEST_NOT_FOUND]: 'Digest not found',
  [errorCodes.DIGEST_ALREADY_RUNNING]: 'A digest is already being written for this snapshot',
  [errorCodes.DIGEST_RUNNER_UNAVAILABLE]: 'The coding agent could not be found on this computer',
  [errorCodes.PARENT_CYCLE]: 'That parent already builds on this branch',
  [errorCodes.BRANCH_NOT_CHECKED_OUT]: 'The branch is not checked out, so it has no working changes',
  [errorCodes.CONNECTION_NOT_FOUND]: 'Connection not found',
  [errorCodes.CONNECTION_REJECTED]: 'The token was rejected. Check that it is valid and has read access',
  [errorCodes.CODE_HOST_UNREACHABLE]: 'Could not reach the server. Check the address and your network',
  [errorCodes.CODE_HOST_ERROR]: 'The server returned an error',
  [errorCodes.REMOTE_PROJECT_NOT_FOUND]: 'This repository has no GitLab or GitHub project linked',
  [errorCodes.CHANGE_REQUEST_NOT_FOUND]: 'Merge request not found',
  [errorCodes.CHANGE_REQUEST_ALREADY_LINKED]: 'That merge request already has its own review',
  [errorCodes.SECRETS_UNAVAILABLE]: 'This computer has no secure storage for tokens',
  [errorCodes.CODE_HOST_WRITE_REJECTED]:
    'The host refused to post. Comments need a token with write access (the api scope on GitLab, pull requests: write on GitHub)',
  [errorCodes.REVIEW_ALREADY_PENDING]:
    'You already have a pending review on this pull request. Submit or delete it on GitHub first',
  [errorCodes.NOT_A_CHANGE_REQUEST]: 'Only merge requests and pull requests can take comments',
  [errorCodes.NOTHING_TO_POST]: 'None of the selected findings can be posted; they were posted already',
  [errorCodes.INVALID_AGENT_REPORT]: 'The report is not JSON Chaff understands',
  [errorCodes.FIX_NOT_FOUND]: 'Fix not found',
  [errorCodes.FIX_ALREADY_RUNNING]: 'An agent is already working on fixes for this review',
  [errorCodes.FIX_STILL_RUNNING]: 'Stop the agent before discarding its fix',
  [errorCodes.PREFERENCE_NOT_FOUND]: 'Preference not found',
  [errorCodes.SHORTCUT_CONFLICT]: 'Two actions on the same screen cannot share a key',
  [errorCodes.NOTHING_TO_FIX]: 'None of the selected findings is open for the agent to work on',
  [errorCodes.CHANGE_UNIT_NOT_FOUND]: 'Change not found in this snapshot',
});
